# Generated by Django 2.2 on 2022-05-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_perttynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perttynum',
            name='mobile',
            field=models.CharField(max_length=1, verbose_name='手机号'),
        ),
    ]
