# Generated by Django 2.2 on 2022-05-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220506_0937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PerttyNum',
            new_name='PrettyNum',
        ),
    ]
