# Generated by Django 2.2 on 2022-05-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='satus',
            new_name='status',
        ),
    ]
